;
; File generated by cc65 v 2.17 - Raspbian 2.17-1
;
	.fopt		compiler,"cc65 v 2.17 - Raspbian 2.17-1"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.importzp	_InputPort1
	.importzp	_InputPort2
	.import		_WaitFrame
	.export		_PALETTES
	.export		_i
	.export		_j
	.export		_STATE
	.export		_START1_X
	.export		_START1_Y
	.export		_START2_X
	.export		_START2_Y
	.export		_SPEED
	.export		_SPEED2
	.export		_SCORE1
	.export		_SCORE2
	.export		_B_TOP
	.export		_B_BOT
	.export		_B_RGT
	.export		_B_LFT
	.export		_P1_TOP
	.export		_P1_BOT
	.export		_P1_RGT
	.export		_P1_LFT
	.export		_P2_TOP
	.export		_P2_BOT
	.export		_P2_RGT
	.export		_P2_LFT
	.export		_tmp_sprite
	.export		_ppu_addr
	.export		_ppu_data
	.export		_ppu_data_size
	.export		_player1
	.export		_player2
	.export		_score1
	.export		_score2
	.export		_ResetScroll
	.export		_EnablePPU
	.export		_WritePPU
	.export		_DrawArena
	.export		_DrawTitle
	.export		_Title_Setup
	.export		_Title_Loop
	.export		_Game_Setup
	.export		_Game_Loop
	.export		_main

.segment	"RODATA"

_PALETTES:
	.byte	$0F
	.byte	$16
	.byte	$27
	.byte	$18
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$22
	.byte	$16
	.byte	$27
	.byte	$18
	.byte	$0F
	.byte	$28
	.byte	$1A
	.byte	$12
	.byte	$00
	.byte	$20
	.byte	$28
	.byte	$17
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00

.segment	"BSS"

.segment	"ZEROPAGE"
_i:
	.res	1,$00
_j:
	.res	1,$00
_STATE:
	.res	1,$00
_START1_X:
	.res	1,$00
_START1_Y:
	.res	1,$00
_START2_X:
	.res	1,$00
_START2_Y:
	.res	1,$00
_SPEED:
	.res	1,$00
_SPEED2:
	.res	1,$00
_SCORE1:
	.res	1,$00
_SCORE2:
	.res	1,$00
_B_TOP:
	.res	1,$00
_B_BOT:
	.res	1,$00
_B_RGT:
	.res	1,$00
_B_LFT:
	.res	1,$00
_P1_TOP:
	.res	1,$00
_P1_BOT:
	.res	1,$00
_P1_RGT:
	.res	1,$00
_P1_LFT:
	.res	1,$00
_P2_TOP:
	.res	1,$00
_P2_BOT:
	.res	1,$00
_P2_RGT:
	.res	1,$00
_P2_LFT:
	.res	1,$00
_tmp_sprite:
	.res	1,$00
_ppu_addr:
	.res	2,$00
_ppu_data:
	.res	2,$00
_ppu_data_size:
	.res	1,$00
.segment	"OAM"
_player1:
	.res	4,$00
_player2:
	.res	4,$00
_score1:
	.res	4,$00
_score2:
	.res	4,$00

; ---------------------------------------------------------------
; void __near__ ResetScroll (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_ResetScroll: near

.segment	"CODE"

;
; PPU_SCROLL = 0x00;
;
	lda     #$00
	sta     $2005
;
; PPU_SCROLL = 0x00;
;
	sta     $2005
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ EnablePPU (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_EnablePPU: near

.segment	"CODE"

;
; PPU_CTRL = PPUCTRL_NAMETABLE_0 | PPUCTRL_BPATTERN_0 | PPUCTRL_NMI_ON;
;
	lda     #$80
	sta     $2000
;
; PPUMASK_SSHOW       | PPUMASK_L8_SSHOW;;
;
	lda     #$1E
	sta     $2001
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ WritePPU (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_WritePPU: near

.segment	"CODE"

;
; PPU_ADDRESS = (uint8_t)(ppu_addr >> 8);
;
	lda     _ppu_addr+1
	sta     $2006
;
; PPU_ADDRESS = (uint8_t)(ppu_addr);
;
	lda     _ppu_addr
	sta     $2006
;
; for (i = 0; i < ppu_data_size; ++i) 
;
	lda     #$00
	sta     _i
L0428:	lda     _i
	cmp     _ppu_data_size
	bcs     L0042
;
; PPU_DATA = ppu_data[i];
;
	lda     _ppu_data
	ldx     _ppu_data+1
	ldy     _i
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	sta     $2007
;
; for (i = 0; i < ppu_data_size; ++i) 
;
	inc     _i
	jmp     L0428
;
; }
;
L0042:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ DrawArena (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DrawArena: near

.segment	"CODE"

;
; PPU_DATA = BORDER_TL;
;
	lda     #$04
	sta     $2007
;
; for(i = 0; i < (NUM_COLS - 2); ++i)
;
	lda     #$00
	sta     _i
L0429:	lda     _i
	cmp     #$1E
	bcs     L042A
;
; PPU_DATA = BORDER_T;
;
	lda     #$07
	sta     $2007
;
; for(i = 0; i < (NUM_COLS - 2); ++i)
;
	inc     _i
	jmp     L0429
;
; PPU_DATA = BORDER_TR;
;
L042A:	lda     #$05
	sta     $2007
;
; PPU_DATA = BORDER_L;
;
	lda     #$06
	sta     $2007
;
; for (j = 0; j < ((NUM_COLS / 2) - 7); j++)
;
	lda     #$00
	sta     _j
L042B:	lda     _j
	cmp     #$09
	bcs     L042C
;
; PPU_DATA = BLANK_TILE;
;
	lda     #$00
	sta     $2007
;
; for (j = 0; j < ((NUM_COLS / 2) - 7); j++)
;
	inc     _j
	jmp     L042B
;
; tmp_sprite = 0xA0;
;
L042C:	lda     #$A0
	sta     _tmp_sprite
;
; for (j = 0; j < (12); j++)
;
	lda     #$00
	sta     _j
L042D:	lda     _j
	cmp     #$0C
	bcs     L042E
;
; PPU_DATA = tmp_sprite;
;
	lda     _tmp_sprite
	sta     $2007
;
; tmp_sprite++;
;
	inc     _tmp_sprite
;
; for (j = 0; j < (12); j++)
;
	inc     _j
	jmp     L042D
;
; for (j = 0; j < ((NUM_COLS / 2) - 7); j++)
;
L042E:	lda     #$00
	sta     _j
L042F:	lda     _j
	cmp     #$09
	bcs     L0430
;
; PPU_DATA = BLANK_TILE;
;
	lda     #$00
	sta     $2007
;
; for (j = 0; j < ((NUM_COLS / 2) - 7); j++)
;
	inc     _j
	jmp     L042F
;
; PPU_DATA = BORDER_R;
;
L0430:	lda     #$16
	sta     $2007
;
; PPU_DATA = BORDER_L;
;
	lda     #$06
	sta     $2007
;
; for (j = 0; j < ((NUM_COLS / 2) - 7); j++)
;
	lda     #$00
	sta     _j
L0431:	lda     _j
	cmp     #$09
	bcs     L0432
;
; PPU_DATA = BLANK_TILE;
;
	lda     #$00
	sta     $2007
;
; for (j = 0; j < ((NUM_COLS / 2) - 7); j++)
;
	inc     _j
	jmp     L0431
;
; tmp_sprite = 0xB0;
;
L0432:	lda     #$B0
	sta     _tmp_sprite
;
; for (j = 0; j < (12); j++)
;
	lda     #$00
	sta     _j
L0433:	lda     _j
	cmp     #$0C
	bcs     L0434
;
; PPU_DATA = tmp_sprite;
;
	lda     _tmp_sprite
	sta     $2007
;
; tmp_sprite++;
;
	inc     _tmp_sprite
;
; for (j = 0; j < (12); j++)
;
	inc     _j
	jmp     L0433
;
; for (j = 0; j < ((NUM_COLS / 2) - 7); j++)
;
L0434:	lda     #$00
	sta     _j
L0435:	lda     _j
	cmp     #$09
	bcs     L0436
;
; PPU_DATA = BLANK_TILE;
;
	lda     #$00
	sta     $2007
;
; for (j = 0; j < ((NUM_COLS / 2) - 7); j++)
;
	inc     _j
	jmp     L0435
;
; PPU_DATA = BORDER_R;
;
L0436:	lda     #$16
	sta     $2007
;
; for (i = 0; i < (NUM_ROWS - 4); ++i)
;
	lda     #$00
	sta     _i
L0437:	lda     _i
	cmp     #$18
	bcs     L043A
;
; PPU_DATA = BORDER_L;
;
	lda     #$06
	sta     $2007
;
; for (j = 0; j < (NUM_COLS - 2); ++j)
;
	lda     #$00
	sta     _j
L0438:	lda     _j
	cmp     #$1E
	bcs     L0439
;
; PPU_DATA = BLANK_TILE;
;
	lda     #$00
	sta     $2007
;
; for (j = 0; j < (NUM_COLS - 2); ++j)
;
	inc     _j
	jmp     L0438
;
; PPU_DATA = BORDER_R;
;
L0439:	lda     #$16
	sta     $2007
;
; for (i = 0; i < (NUM_ROWS - 4); ++i)
;
	inc     _i
	jmp     L0437
;
; PPU_DATA = BORDER_BL;
;
L043A:	lda     #$14
	sta     $2007
;
; for(i = 0; i < (NUM_COLS - 2); ++i)
;
	lda     #$00
	sta     _i
L043B:	lda     _i
	cmp     #$1E
	bcs     L043C
;
; PPU_DATA = BORDER_B;
;
	lda     #$17
	sta     $2007
;
; for(i = 0; i < (NUM_COLS - 2); ++i)
;
	inc     _i
	jmp     L043B
;
; PPU_DATA = BORDER_BR;
;
L043C:	lda     #$15
	sta     $2007
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ DrawTitle (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DrawTitle: near

.segment	"CODE"

;
; PPU_DATA = BORDER_TL;
;
	lda     #$04
	sta     $2007
;
; for(i = 0; i < (NUM_COLS - 2); ++i)
;
	lda     #$00
	sta     _i
L043D:	lda     _i
	cmp     #$1E
	bcs     L043E
;
; PPU_DATA = BORDER_T;
;
	lda     #$07
	sta     $2007
;
; for(i = 0; i < (NUM_COLS - 2); ++i)
;
	inc     _i
	jmp     L043D
;
; PPU_DATA = BORDER_TR;
;
L043E:	lda     #$05
	sta     $2007
;
; PPU_DATA = BORDER_L;
;
	lda     #$06
	sta     $2007
;
; for (j = 0; j < ((NUM_COLS / 2) - 7); j++)
;
	lda     #$00
	sta     _j
L043F:	lda     _j
	cmp     #$09
	bcs     L0440
;
; PPU_DATA = BLANK_TILE;
;
	lda     #$00
	sta     $2007
;
; for (j = 0; j < ((NUM_COLS / 2) - 7); j++)
;
	inc     _j
	jmp     L043F
;
; tmp_sprite = 0xA0;
;
L0440:	lda     #$A0
	sta     _tmp_sprite
;
; for (j = 0; j < (12); j++)
;
	lda     #$00
	sta     _j
L0441:	lda     _j
	cmp     #$0C
	bcs     L0442
;
; PPU_DATA = tmp_sprite;
;
	lda     _tmp_sprite
	sta     $2007
;
; tmp_sprite++;
;
	inc     _tmp_sprite
;
; for (j = 0; j < (12); j++)
;
	inc     _j
	jmp     L0441
;
; for (j = 0; j < ((NUM_COLS / 2) - 7); j++)
;
L0442:	lda     #$00
	sta     _j
L0443:	lda     _j
	cmp     #$09
	bcs     L0444
;
; PPU_DATA = BLANK_TILE;
;
	lda     #$00
	sta     $2007
;
; for (j = 0; j < ((NUM_COLS / 2) - 7); j++)
;
	inc     _j
	jmp     L0443
;
; PPU_DATA = BORDER_R;
;
L0444:	lda     #$16
	sta     $2007
;
; PPU_DATA = BORDER_L;
;
	lda     #$06
	sta     $2007
;
; for (j = 0; j < ((NUM_COLS / 2) - 7); j++)
;
	lda     #$00
	sta     _j
L0445:	lda     _j
	cmp     #$09
	bcs     L0446
;
; PPU_DATA = BLANK_TILE;
;
	lda     #$00
	sta     $2007
;
; for (j = 0; j < ((NUM_COLS / 2) - 7); j++)
;
	inc     _j
	jmp     L0445
;
; tmp_sprite = 0xB0;
;
L0446:	lda     #$B0
	sta     _tmp_sprite
;
; for (j = 0; j < (12); j++)
;
	lda     #$00
	sta     _j
L0447:	lda     _j
	cmp     #$0C
	bcs     L0448
;
; PPU_DATA = tmp_sprite;
;
	lda     _tmp_sprite
	sta     $2007
;
; tmp_sprite++;
;
	inc     _tmp_sprite
;
; for (j = 0; j < (12); j++)
;
	inc     _j
	jmp     L0447
;
; for (j = 0; j < ((NUM_COLS / 2) - 7); j++)
;
L0448:	lda     #$00
	sta     _j
L0449:	lda     _j
	cmp     #$09
	bcs     L044A
;
; PPU_DATA = BLANK_TILE;
;
	lda     #$00
	sta     $2007
;
; for (j = 0; j < ((NUM_COLS / 2) - 7); j++)
;
	inc     _j
	jmp     L0449
;
; PPU_DATA = BORDER_R;
;
L044A:	lda     #$16
	sta     $2007
;
; for (i = 0; i < ((NUM_ROWS/2) - 4); ++i)
;
	lda     #$00
	sta     _i
L044B:	lda     _i
	cmp     #$0A
	bcs     L044E
;
; PPU_DATA = BORDER_L;
;
	lda     #$06
	sta     $2007
;
; for (j = 0; j < (NUM_COLS - 2); ++j)
;
	lda     #$00
	sta     _j
L044C:	lda     _j
	cmp     #$1E
	bcs     L044D
;
; PPU_DATA = BLANK_TILE;
;
	lda     #$00
	sta     $2007
;
; for (j = 0; j < (NUM_COLS - 2); ++j)
;
	inc     _j
	jmp     L044C
;
; PPU_DATA = BORDER_R;
;
L044D:	lda     #$16
	sta     $2007
;
; for (i = 0; i < ((NUM_ROWS/2) - 4); ++i)
;
	inc     _i
	jmp     L044B
;
; PPU_DATA = BORDER_L;
;
L044E:	lda     #$06
	sta     $2007
;
; for ( j = 0; j < (NUM_COLS / 2) - 7; ++j)
;
	lda     #$00
	sta     _j
L044F:	lda     _j
	cmp     #$09
	bcs     L0450
;
; PPU_DATA = BLANK_TILE;
;
	lda     #$00
	sta     $2007
;
; for ( j = 0; j < (NUM_COLS / 2) - 7; ++j)
;
	inc     _j
	jmp     L044F
;
; PPU_DATA = 0x70;
;
L0450:	lda     #$70
	sta     $2007
;
; PPU_DATA = 0x72;
;
	lda     #$72
	sta     $2007
;
; PPU_DATA = 0x65;
;
	lda     #$65
	sta     $2007
;
; PPU_DATA = 0x73;
;
	lda     #$73
	sta     $2007
;
; PPU_DATA = 0x73;
;
	sta     $2007
;
; PPU_DATA = BLANK_TILE;
;
	lda     #$00
	sta     $2007
;
; PPU_DATA = BLANK_TILE;
;
	sta     $2007
;
; PPU_DATA = 0x73;
;
	lda     #$73
	sta     $2007
;
; PPU_DATA = 0x74;
;
	lda     #$74
	sta     $2007
;
; PPU_DATA = 0x61;
;
	lda     #$61
	sta     $2007
;
; PPU_DATA = 0x72;
;
	lda     #$72
	sta     $2007
;
; PPU_DATA = 0x74; 
;
	lda     #$74
	sta     $2007
;
; for ( j = 0; j < (NUM_COLS / 2) - 7; ++j)
;
	lda     #$00
	sta     _j
L0451:	lda     _j
	cmp     #$09
	bcs     L0452
;
; PPU_DATA = BLANK_TILE;
;
	lda     #$00
	sta     $2007
;
; for ( j = 0; j < (NUM_COLS / 2) - 7; ++j)
;
	inc     _j
	jmp     L0451
;
; PPU_DATA = BORDER_R;
;
L0452:	lda     #$16
	sta     $2007
;
; for (i = 0; i < ((NUM_ROWS/2) - 1); ++i)
;
	lda     #$00
	sta     _i
L0453:	lda     _i
	cmp     #$0D
	bcs     L0456
;
; PPU_DATA = BORDER_L;
;
	lda     #$06
	sta     $2007
;
; for (j = 0; j < (NUM_COLS - 2); ++j)
;
	lda     #$00
	sta     _j
L0454:	lda     _j
	cmp     #$1E
	bcs     L0455
;
; PPU_DATA = BLANK_TILE;
;
	lda     #$00
	sta     $2007
;
; for (j = 0; j < (NUM_COLS - 2); ++j)
;
	inc     _j
	jmp     L0454
;
; PPU_DATA = BORDER_R;
;
L0455:	lda     #$16
	sta     $2007
;
; for (i = 0; i < ((NUM_ROWS/2) - 1); ++i)
;
	inc     _i
	jmp     L0453
;
; PPU_DATA = BORDER_BL;
;
L0456:	lda     #$14
	sta     $2007
;
; for(i = 0; i < (NUM_COLS - 2); ++i)
;
	lda     #$00
	sta     _i
L0457:	lda     _i
	cmp     #$1E
	bcs     L0458
;
; PPU_DATA = BORDER_B;
;
	lda     #$17
	sta     $2007
;
; for(i = 0; i < (NUM_COLS - 2); ++i)
;
	inc     _i
	jmp     L0457
;
; PPU_DATA = BORDER_BR;
;
L0458:	lda     #$15
	sta     $2007
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ Title_Setup (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Title_Setup: near

.segment	"CODE"

;
; START1_X = (MAX_X / 2) - (SPRITE_WIDTH  / 2) - 60;
;
	lda     #$40
	sta     _START1_X
;
; START1_Y = (MAX_Y / 2) - (SPRITE_HEIGHT / 2);
;
	lda     #$6F
	sta     _START1_Y
;
; START2_X = (MAX_X / 2) - (SPRITE_WIDTH  / 2) + 60;
;
	lda     #$B8
	sta     _START2_X
;
; START2_Y = (MAX_Y / 2) - (SPRITE_HEIGHT / 2);
;
	lda     #$6F
	sta     _START2_Y
;
; SCORE1 = 0;
;
	lda     #$00
	sta     _SCORE1
;
; WritePPU();
;
	jsr     _WritePPU
;
; player1.x           = START1_X; 
;
	lda     _START1_X
	sta     _player1+3
;
; player1.y           = START1_Y;
;
	lda     _START1_Y
	sta     _player1
;
; player1.tile_index  = SPRITE_RIGHT;
;
	lda     #$11
	sta     _player1+1
;
; player1.attributes  = player1.attributes & 0x00;
;
	lda     #$00
	sta     _player1+2
;
; player2.x           = START2_X;
;
	lda     _START2_X
	sta     _player2+3
;
; player2.y           = START2_Y;
;
	lda     _START2_Y
	sta     _player2
;
; player2.tile_index  = SPRITE_LEFT;
;
	lda     #$12
	sta     _player2+1
;
; player2.attributes  = player2.attributes & 0x00;
;
	lda     #$00
	sta     _player2+2
;
; player2.attributes  = player2.attributes | 0x01;
;
	lda     #$01
	sta     _player2+2
;
; ResetScroll();
;
	jsr     _ResetScroll
;
; EnablePPU();
;
	jmp     _EnablePPU

.endproc

; ---------------------------------------------------------------
; void __near__ Title_Loop (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Title_Loop: near

.segment	"CODE"

;
; while(SCORE1 == 0)
;
	jmp     L045A
;
; WaitFrame();
;
L0211:	jsr     _WaitFrame
;
; ResetScroll();
;
	jsr     _ResetScroll
;
; if(InputPort1 & BUTTON_START)
;
	lda     _InputPort1
	and     #$10
	beq     L0459
;
; SCORE1++;
;
	inc     _SCORE1
;
; if(InputPort2 & BUTTON_START)
;
L0459:	lda     _InputPort2
	and     #$10
	beq     L045A
;
; SCORE1++;
;
	inc     _SCORE1
;
; while(SCORE1 == 0)
;
L045A:	lda     _SCORE1
	beq     L0211
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ Game_Setup (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Game_Setup: near

.segment	"CODE"

;
; B_TOP = MIN_Y + SPRITE_HEIGHT;
;
	lda     #$10
	sta     _B_TOP
;
; B_BOT = MAX_Y - (SPRITE_HEIGHT + SPRITE_HEIGHT);
;
	lda     #$D7
	sta     _B_BOT
;
; B_RGT = MAX_X - (SPRITE_WIDTH + SPRITE_WIDTH);
;
	lda     #$F0
	sta     _B_RGT
;
; B_LFT = MIN_X + SPRITE_WIDTH;
;
	lda     #$08
	sta     _B_LFT
;
; START1_X = (MAX_X / 2) - (SPRITE_WIDTH  / 2) - 50;
;
	lda     #$4A
	sta     _START1_X
;
; START1_Y = (MAX_Y / 2) - (SPRITE_HEIGHT / 2);
;
	lda     #$6F
	sta     _START1_Y
;
; START2_X = (MAX_X / 2) - (SPRITE_WIDTH  / 2) + 50;
;
	lda     #$AE
	sta     _START2_X
;
; START2_Y = (MAX_Y / 2) - (SPRITE_HEIGHT / 2);
;
	lda     #$6F
	sta     _START2_Y
;
; SPEED =  SPRINT;
;
	lda     #$03
	sta     _SPEED
;
; SPEED2 = SPRINT;
;
	sta     _SPEED2
;
; SCORE1 = 0;
;
	lda     #$00
	sta     _SCORE1
;
; SCORE2 = 0;
;
	sta     _SCORE2
;
; player1.x           = START1_X; 
;
	lda     _START1_X
	sta     _player1+3
;
; player1.y           = START1_Y;
;
	lda     _START1_Y
	sta     _player1
;
; player1.tile_index  = SPRITE_RIGHT;
;
	lda     #$11
	sta     _player1+1
;
; player1.attributes  = player1.attributes & 0x00;
;
	lda     #$00
	sta     _player1+2
;
; player2.x           = START2_X;
;
	lda     _START2_X
	sta     _player2+3
;
; player2.y           = START2_Y;
;
	lda     _START2_Y
	sta     _player2
;
; player2.tile_index  = SPRITE_LEFT;
;
	lda     #$12
	sta     _player2+1
;
; player2.attributes  = player2.attributes & 0x00;
;
	lda     #$00
	sta     _player2+2
;
; player2.attributes  = player2.attributes | 0x01;
;
	lda     #$01
	sta     _player2+2
;
; score1.x = MIN_X + SPRITE_WIDTH;
;
	lda     #$08
	sta     _score1+3
;
; score1.y = MIN_Y + SPRITE_HEIGHT;
;
	lda     #$10
	sta     _score1
;
; score1.tile_index   = 0x55;
;
	lda     #$55
	sta     _score1+1
;
; score1.attributes   = player1.attributes;
;
	lda     _player1+2
	sta     _score1+2
;
; score2.x = MAX_X - SPRITE_WIDTH - SPRITE_WIDTH;
;
	lda     #$F0
	sta     _score2+3
;
; score2.y = MIN_Y + SPRITE_HEIGHT;
;
	lda     #$10
	sta     _score2
;
; score2.tile_index   = 0x55;
;
	lda     #$55
	sta     _score2+1
;
; score2.attributes   = score2.attributes;
;
	lda     _score2+2
	sta     _score2+2
;
; ResetScroll();
;
	jsr     _ResetScroll
;
; EnablePPU();
;
	jmp     _EnablePPU

.endproc

; ---------------------------------------------------------------
; void __near__ Game_Loop (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Game_Loop: near

.segment	"CODE"

;
; while (SCORE1 < 5 && SCORE2 < 5)
;
	jmp     L0267
;
; P1_TOP = player1.y + SPRITE_HEIGHT;
;
L0479:	lda     _player1
	clc
	adc     #$08
	sta     _P1_TOP
;
; P1_BOT = player1.y - SPRITE_HEIGHT;
;
	lda     _player1
	sec
	sbc     #$08
	sta     _P1_BOT
;
; P1_RGT = player1.x + SPRITE_HEIGHT;
;
	lda     _player1+3
	clc
	adc     #$08
	sta     _P1_RGT
;
; P1_LFT = player1.x - SPRITE_HEIGHT;
;
	lda     _player1+3
	sec
	sbc     #$08
	sta     _P1_LFT
;
; P2_TOP = player2.y + SPRITE_HEIGHT;
;
	lda     _player2
	clc
	adc     #$08
	sta     _P2_TOP
;
; P2_BOT = player2.y - SPRITE_HEIGHT;
;
	lda     _player2
	sec
	sbc     #$08
	sta     _P2_BOT
;
; P2_RGT = player2.x + SPRITE_HEIGHT;
;
	lda     _player2+3
	clc
	adc     #$08
	sta     _P2_RGT
;
; P2_LFT = player2.x - SPRITE_HEIGHT;
;
	lda     _player2+3
	sec
	sbc     #$08
	sta     _P2_LFT
;
; if (InputPort1 & BUTTON_UP)
;
	lda     _InputPort1
	and     #$08
	jeq     L0482
;
; player1.tile_index  = SPRITE_UP;
;
	lda     #$13
	sta     _player1+1
;
; if (player1.y > B_TOP)
;
	lda     _player1
	sec
	sbc     _B_TOP
	jcc     L049C
	jeq     L049C
;
; if (player1.y >= player2.y)
;
	lda     _player1
	cmp     _player2
	bcc     L0481
;
; if( P1_RGT >= player2.x &&
;
	lda     _P1_RGT
	cmp     _player2+3
	bcc     L0480
;
; P1_LFT <= player2.x)
;
	lda     _P1_LFT
	sec
	sbc     _player2+3
	bcc     L047C
	bne     L0480
;
; if(P1_BOT <= player2.y)
;
L047C:	lda     _P1_BOT
	sec
	sbc     _player2
	sta     tmp1
	lda     tmp1
	beq     L047D
	bcs     L0481
;
; if(player2.tile_index != SPRITE_DOWN)
;
L047D:	lda     _player2+1
	cmp     #$10
	beq     L047E
;
; SCORE1++;
;
	inc     _SCORE1
;
; score2.tile_index = score2.tile_index - 1;
;
	lda     _score2+1
	sec
	sbc     #$01
	sta     _score2+1
;
; player1.x = START1_X;
;
L047E:	lda     _START1_X
	sta     _player1+3
;
; player1.y = START1_Y;
;
	lda     _START1_Y
	sta     _player1
;
; player1.tile_index = SPRITE_RIGHT;
;
	lda     #$11
	sta     _player1+1
;
; player2.x = START2_X;
;
	lda     _START2_X
	sta     _player2+3
;
; player2.y = START2_Y;
;
	lda     _START2_Y
	sta     _player2
;
; player2.tile_index = SPRITE_LEFT;
;
	lda     #$12
	sta     _player2+1
;
; else 
;
	jmp     L049C
;
; player1.y = player1.y - SPEED;
;
L0480:	lda     _player1
	sec
	sbc     _SPEED
	sta     _player1
;
; else 
;
	jmp     L049C
;
; player1.y = player1.y - SPEED;
;
L0481:	lda     _player1
	sec
	sbc     _SPEED
	sta     _player1
;
; else if (InputPort1 & BUTTON_DOWN)  
;
	jmp     L049C
L0482:	lda     _InputPort1
	and     #$04
	jeq     L048B
;
; player1.tile_index  = SPRITE_DOWN; 
;
	lda     #$10
	sta     _player1+1
;
; if (player1.y < B_BOT)
;
	lda     _player1
	cmp     _B_BOT
	jcs     L049C
;
; if (player1.y <= player2.y)
;
	sec
	sbc     _player2
	sta     tmp1
	lda     tmp1
	beq     L0483
	bcs     L048A
;
; if(P1_RGT >= player2.x &&
;
L0483:	lda     _P1_RGT
	cmp     _player2+3
	bcc     L0489
;
; P1_LFT <= player2.x)
;
	lda     _P1_LFT
	sec
	sbc     _player2+3
	bcc     L0486
	bne     L0489
;
; if(P1_TOP >= player2.y)
;
L0486:	lda     _P1_TOP
	cmp     _player2
	bcc     L048A
;
; if(player2.tile_index != SPRITE_UP)
;
	lda     _player2+1
	cmp     #$13
	beq     L0487
;
; SCORE1++;
;
	inc     _SCORE1
;
; score2.tile_index = score2.tile_index - 1;
;
	lda     _score2+1
	sec
	sbc     #$01
	sta     _score2+1
;
; player1.x = START1_X;
;
L0487:	lda     _START1_X
	sta     _player1+3
;
; player1.y = START1_Y;
;
	lda     _START1_Y
	sta     _player1
;
; player1.tile_index = SPRITE_RIGHT;
;
	lda     #$11
	sta     _player1+1
;
; player2.x = START2_X;
;
	lda     _START2_X
	sta     _player2+3
;
; player2.y = START2_Y;
;
	lda     _START2_Y
	sta     _player2
;
; player2.tile_index = SPRITE_LEFT;
;
	lda     #$12
	sta     _player2+1
;
; else 
;
	jmp     L049C
;
; player1.y = player1.y + SPEED;
;
L0489:	lda     _player1
	clc
	adc     _SPEED
	sta     _player1
;
; else 
;
	jmp     L049C
;
; player1.y = player1.y + SPEED;
;
L048A:	lda     _player1
	clc
	adc     _SPEED
	sta     _player1
;
; else if (InputPort1 & BUTTON_LEFT)  
;
	jmp     L049C
L048B:	lda     _InputPort1
	and     #$02
	jeq     L0493
;
; player1.tile_index  = SPRITE_LEFT; 
;
	lda     #$12
	sta     _player1+1
;
; if (player1.x > B_LFT)
;
	ldx     #$00
	lda     _player1+3
	sec
	sbc     _B_LFT
	jcc     L049C
	jeq     L049C
;
; if (player1.x >= player2.x)
;
	lda     _player1+3
	cmp     _player2+3
	jcc     L0492
;
; if(player1.y + SPRITE_HEIGHT >= player2.y &&
;
	lda     _player1
	clc
	adc     #$08
	bcc     L02E1
	inx
L02E1:	cmp     _player2
	txa
	sbc     #$00
	ldx     #$00
	bcc     L0491
;
; player1.y - SPRITE_HEIGHT <= player2.y)
;
	lda     _player1
	sec
	sbc     #$08
	bcs     L0478
	dex
	sec
L0478:	sbc     _player2
	sta     tmp1
	txa
	sbc     #$00
	ora     tmp1
	bcc     L02E0
	bne     L0491
;
; if(P1_LFT <= player2.x)
;
L02E0:	lda     _P1_LFT
	sec
	sbc     _player2+3
	sta     tmp1
	lda     tmp1
	beq     L048E
	bcs     L0490
;
; if(player2.tile_index != SPRITE_RIGHT)
;
L048E:	lda     _player2+1
	cmp     #$11
	beq     L048F
;
; SCORE1++;
;
	inc     _SCORE1
;
; score2.tile_index = score2.tile_index - 1;
;
	lda     _score2+1
	sec
	sbc     #$01
	sta     _score2+1
;
; player1.x = START1_X; 
;
L048F:	lda     _START1_X
	sta     _player1+3
;
; player1.y = START1_Y;
;
	lda     _START1_Y
	sta     _player1
;
; player1.tile_index = SPRITE_RIGHT;
;
	lda     #$11
	sta     _player1+1
;
; player2.x = START2_X;
;
	lda     _START2_X
	sta     _player2+3
;
; player2.y = START2_Y;
;
	lda     _START2_Y
	sta     _player2
;
; player2.tile_index = SPRITE_LEFT;
;
	lda     #$12
	sta     _player2+1
;
; else 
;
	jmp     L049C
;
; player1.x = player1.x - SPEED;
;
L0490:	lda     _player1+3
	sec
	sbc     _SPEED
;
; else
;
	jmp     L0473
;
; player1.x = player1.x - SPEED;
;
L0491:	lda     _player1+3
	sec
	sbc     _SPEED
;
; else 
;
	jmp     L0473
;
; player1.x = player1.x - SPEED;
;
L0492:	lda     _player1+3
	sec
	sbc     _SPEED
;
; else if (InputPort1 & BUTTON_RIGHT)  
;
	jmp     L0473
L0493:	lda     _InputPort1
	and     #$01
	beq     L049C
;
; player1.tile_index  = SPRITE_RIGHT;
;
	lda     #$11
	sta     _player1+1
;
; if (player1.x < B_RGT)   
;
	lda     _player1+3
	cmp     _B_RGT
	bcs     L049C
;
; if (player1.x <= player2.x)
;
	sec
	sbc     _player2+3
	sta     tmp1
	lda     tmp1
	beq     L0494
	bcs     L049B
;
; if(P1_TOP >= player2.y &&
;
L0494:	lda     _P1_TOP
	cmp     _player2
	bcc     L049B
;
; P1_BOT <= player2.y)
;
	lda     _P1_BOT
	sec
	sbc     _player2
	bcc     L0497
	bne     L049B
;
; if(P1_RGT >= player2.x)
;
L0497:	lda     _P1_RGT
	cmp     _player2+3
	bcc     L049B
;
; if(player2.tile_index != SPRITE_LEFT)
;
	lda     _player2+1
	cmp     #$12
	beq     L0498
;
; SCORE1++;
;
	inc     _SCORE1
;
; score2.tile_index = score2.tile_index - 1;
;
	lda     _score2+1
	sec
	sbc     #$01
	sta     _score2+1
;
; player1.x = START1_X; 
;
L0498:	lda     _START1_X
	sta     _player1+3
;
; player1.y = START1_Y;
;
	lda     _START1_Y
	sta     _player1
;
; player1.tile_index = SPRITE_RIGHT;
;
	lda     #$11
	sta     _player1+1
;
; player2.x = START2_X;
;
	lda     _START2_X
	sta     _player2+3
;
; player2.y = START2_Y;
;
	lda     _START2_Y
	sta     _player2
;
; player2.tile_index = SPRITE_LEFT;                          
;
	lda     #$12
	sta     _player2+1
;
; else 
;
	jmp     L049C
;
; player1.x = player1.x + SPEED;
;
L049B:	lda     _player1+3
	clc
	adc     _SPEED
L0473:	sta     _player1+3
;
; if (InputPort2 & BUTTON_UP)
;
L049C:	lda     _InputPort2
	and     #$08
	jeq     L04A5
;
; player2.tile_index  = SPRITE_UP;
;
	lda     #$13
	sta     _player2+1
;
; if (player2.y > B_TOP)
;
	lda     _player2
	sec
	sbc     _B_TOP
	jcc     L04C0
	jeq     L04C0
;
; if (player2.y >= player1.y)
;
	lda     _player2
	cmp     _player1
	bcc     L04A4
;
; if( P2_RGT >= player1.x &&
;
	lda     _P2_RGT
	cmp     _player1+3
	bcc     L04A3
;
; P2_LFT <= player1.x)
;
	lda     _P2_LFT
	sec
	sbc     _player1+3
	bcc     L049F
	bne     L04A3
;
; if(P2_BOT <= player1.y)
;
L049F:	lda     _P2_BOT
	sec
	sbc     _player1
	sta     tmp1
	lda     tmp1
	beq     L04A0
	bcs     L04A4
;
; if(player1.tile_index != SPRITE_DOWN)
;
L04A0:	lda     _player1+1
	cmp     #$10
	beq     L04A1
;
; SCORE2++;
;
	inc     _SCORE2
;
; score1.tile_index = score1.tile_index - 1;
;
	lda     _score1+1
	sec
	sbc     #$01
	sta     _score1+1
;
; player1.x = START1_X;
;
L04A1:	lda     _START1_X
	sta     _player1+3
;
; player1.y = START1_Y;
;
	lda     _START1_Y
	sta     _player1
;
; player1.tile_index = SPRITE_RIGHT;
;
	lda     #$11
	sta     _player1+1
;
; player2.x = START2_X;
;
	lda     _START2_X
	sta     _player2+3
;
; player2.y = START2_Y;
;
	lda     _START2_Y
	sta     _player2
;
; player2.tile_index = SPRITE_LEFT;
;
	lda     #$12
	sta     _player2+1
;
; else 
;
	jmp     L04C0
;
; player2.y = player2.y - SPEED2;
;
L04A3:	lda     _player2
	sec
	sbc     _SPEED2
	sta     _player2
;
; else 
;
	jmp     L04C0
;
; player2.y = player2.y - SPEED2;
;
L04A4:	lda     _player2
	sec
	sbc     _SPEED2
	sta     _player2
;
; else if (InputPort2 & BUTTON_DOWN)  
;
	jmp     L04C0
L04A5:	lda     _InputPort2
	and     #$04
	jeq     L04AE
;
; player2.tile_index  = SPRITE_DOWN; 
;
	lda     #$10
	sta     _player2+1
;
; if (player2.y < B_BOT)
;
	lda     _player2
	cmp     _B_BOT
	jcs     L04C0
;
; if (player2.y <= player1.y)
;
	sec
	sbc     _player1
	sta     tmp1
	lda     tmp1
	beq     L04A6
	bcs     L04AD
;
; if(P2_RGT >= player1.x &&
;
L04A6:	lda     _P2_RGT
	cmp     _player1+3
	bcc     L04AC
;
; P2_LFT <= player1.x)
;
	lda     _P2_LFT
	sec
	sbc     _player1+3
	bcc     L04A9
	bne     L04AC
;
; if(P2_TOP >= player1.y)
;
L04A9:	lda     _P2_TOP
	cmp     _player1
	bcc     L04AD
;
; if(player1.tile_index != SPRITE_UP)
;
	lda     _player1+1
	cmp     #$13
	beq     L04AA
;
; SCORE2++;
;
	inc     _SCORE2
;
; score1.tile_index = score1.tile_index - 1;
;
	lda     _score1+1
	sec
	sbc     #$01
	sta     _score1+1
;
; player1.x = START1_X;
;
L04AA:	lda     _START1_X
	sta     _player1+3
;
; player1.y = START1_Y;
;
	lda     _START1_Y
	sta     _player1
;
; player1.tile_index = SPRITE_RIGHT;
;
	lda     #$11
	sta     _player1+1
;
; player2.x = START2_X;
;
	lda     _START2_X
	sta     _player2+3
;
; player2.y = START2_Y;
;
	lda     _START2_Y
	sta     _player2
;
; player2.tile_index = SPRITE_LEFT;
;
	lda     #$12
	sta     _player2+1
;
; else 
;
	jmp     L04C0
;
; player2.y = player2.y + SPEED2;
;
L04AC:	lda     _player2
	clc
	adc     _SPEED2
	sta     _player2
;
; else 
;
	jmp     L04C0
;
; player2.y = player2.y + SPEED2;
;
L04AD:	lda     _player2
	clc
	adc     _SPEED2
	sta     _player2
;
; else if (InputPort2 & BUTTON_LEFT)  
;
	jmp     L04C0
L04AE:	lda     _InputPort2
	and     #$02
	jeq     L04B7
;
; player2.tile_index  = SPRITE_LEFT; 
;
	lda     #$12
	sta     _player2+1
;
; if (player2.x > B_LFT)
;
	lda     _player2+3
	sec
	sbc     _B_LFT
	jcc     L04C0
	jeq     L04C0
;
; if (player2.x >= player1.x)
;
	lda     _player2+3
	cmp     _player1+3
	bcc     L04B6
;
; if(P2_TOP >= player1.y &&
;
	lda     _P2_TOP
	cmp     _player1
	bcc     L04B5
;
; P2_BOT <= player1.y)
;
	lda     _P2_BOT
	sec
	sbc     _player1
	bcc     L04B1
	bne     L04B5
;
; if(P2_LFT <= player1.x)
;
L04B1:	lda     _P2_LFT
	sec
	sbc     _player1+3
	sta     tmp1
	lda     tmp1
	beq     L04B2
	bcs     L04B4
;
; if(player1.tile_index != SPRITE_RIGHT)
;
L04B2:	lda     _player1+1
	cmp     #$11
	beq     L04B3
;
; SCORE2++;
;
	inc     _SCORE2
;
; score1.tile_index = score1.tile_index - 1;
;
	lda     _score1+1
	sec
	sbc     #$01
	sta     _score1+1
;
; player1.x = START1_X; 
;
L04B3:	lda     _START1_X
	sta     _player1+3
;
; player1.y = START1_Y;
;
	lda     _START1_Y
	sta     _player1
;
; player1.tile_index = SPRITE_RIGHT;
;
	lda     #$11
	sta     _player1+1
;
; player2.x = START2_X;
;
	lda     _START2_X
	sta     _player2+3
;
; player2.y = START2_Y;
;
	lda     _START2_Y
	sta     _player2
;
; player2.tile_index = SPRITE_LEFT;
;
	lda     #$12
	sta     _player2+1
;
; else 
;
	jmp     L04C0
;
; player2.x = player2.x - SPEED2;
;
L04B4:	lda     _player2+3
	sec
	sbc     _SPEED2
;
; else
;
	jmp     L0477
;
; player2.x = player2.x - SPEED2;
;
L04B5:	lda     _player2+3
	sec
	sbc     _SPEED2
;
; else 
;
	jmp     L0477
;
; player2.x = player2.x - SPEED2;
;
L04B6:	lda     _player2+3
	sec
	sbc     _SPEED2
;
; else if (InputPort2 & BUTTON_RIGHT)  
;
	jmp     L0477
L04B7:	lda     _InputPort2
	and     #$01
	beq     L04C0
;
; player2.tile_index  = SPRITE_RIGHT;
;
	lda     #$11
	sta     _player2+1
;
; if (player2.x < B_RGT)   
;
	lda     _player2+3
	cmp     _B_RGT
	bcs     L04C0
;
; if (player2.x <= player1.x)
;
	sec
	sbc     _player1+3
	sta     tmp1
	lda     tmp1
	beq     L04B8
	bcs     L04BF
;
; if(P2_TOP >= player1.y &&
;
L04B8:	lda     _P2_TOP
	cmp     _player1
	bcc     L04BF
;
; P2_BOT <= player1.y)
;
	lda     _P2_BOT
	sec
	sbc     _player1
	bcc     L04BB
	bne     L04BF
;
; if(P2_RGT >= player1.x)
;
L04BB:	lda     _P2_RGT
	cmp     _player1+3
	bcc     L04BF
;
; if(player1.tile_index != SPRITE_LEFT)
;
	lda     _player1+1
	cmp     #$12
	beq     L04BC
;
; SCORE2++;
;
	inc     _SCORE2
;
; score1.tile_index = score1.tile_index - 1;
;
	lda     _score1+1
	sec
	sbc     #$01
	sta     _score1+1
;
; player1.x = START1_X; 
;
L04BC:	lda     _START1_X
	sta     _player1+3
;
; player1.y = START1_Y;
;
	lda     _START1_Y
	sta     _player1
;
; player1.tile_index = SPRITE_RIGHT;
;
	lda     #$11
	sta     _player1+1
;
; player2.x = START2_X;
;
	lda     _START2_X
	sta     _player2+3
;
; player2.y = START2_Y;
;
	lda     _START2_Y
	sta     _player2
;
; player2.tile_index = SPRITE_LEFT;                          
;
	lda     #$12
	sta     _player2+1
;
; else 
;
	jmp     L04C0
;
; player2.x = player2.x + SPEED2;
;
L04BF:	lda     _player2+3
	clc
	adc     _SPEED2
L0477:	sta     _player2+3
;
; if(InputPort1 & BUTTON_SELECT)
;
L04C0:	lda     _InputPort1
	and     #$20
	beq     L04C1
;
; if(InputPort1 & BUTTON_START)
;
L03D5:	lda     _InputPort1
	and     #$10
;
; break;
;
	bne     L04C1
;
; WaitFrame();
;
	jsr     _WaitFrame
;
; ResetScroll();
;
	jsr     _ResetScroll
;
; while(1)
;
	jmp     L03D5
;
; if(InputPort2 & BUTTON_SELECT)
;
L04C1:	lda     _InputPort2
	and     #$20
	beq     L04C2
;
; if(InputPort2 & BUTTON_START)
;
L03DF:	lda     _InputPort2
	and     #$10
;
; break;
;
	bne     L04C2
;
; WaitFrame();
;
	jsr     _WaitFrame
;
; ResetScroll();
;
	jsr     _ResetScroll
;
; while(1)
;
	jmp     L03DF
;
; if (SCORE1 == 5)
;
L04C2:	lda     _SCORE1
	cmp     #$05
	bne     L04C4
;
; score1.tile_index = 0x77;
;
	lda     #$77
	sta     _score1+1
;
; score2.tile_index = 0x6C;
;
	lda     #$6C
	sta     _score2+1
;
; if(InputPort1 & BUTTON_START)
;
L03ED:	lda     _InputPort1
	and     #$10
	beq     L04C3
;
; Game_Setup();
;
	jsr     _Game_Setup
;
; break;
;
	jmp     L04C4
;
; else if (InputPort2 & BUTTON_START)
;
L04C3:	lda     _InputPort2
	and     #$10
	beq     L03F5
;
; Game_Setup();
;
	jsr     _Game_Setup
;
; break;
;
	jmp     L04C4
;
; WaitFrame();
;
L03F5:	jsr     _WaitFrame
;
; ResetScroll();
;
	jsr     _ResetScroll
;
; while(1)
;
	jmp     L03ED
;
; if(SCORE2 == 5)
;
L04C4:	lda     _SCORE2
	cmp     #$05
	bne     L0401
;
; score1.tile_index = 0x6C;
;
	lda     #$6C
	sta     _score1+1
;
; score2.tile_index = 0x77;
;
	lda     #$77
	sta     _score2+1
;
; if(InputPort1 & BUTTON_START)
;
L0400:	lda     _InputPort1
	and     #$10
	beq     L04C5
;
; Game_Setup();
;
	jsr     _Game_Setup
;
; break;
;
	jmp     L0401
;
; else if (InputPort2 & BUTTON_START)
;
L04C5:	lda     _InputPort2
	and     #$10
	beq     L0408
;
; Game_Setup();
;
	jsr     _Game_Setup
;
; break;
;
	jmp     L0401
;
; WaitFrame();
;
L0408:	jsr     _WaitFrame
;
; ResetScroll();
;
	jsr     _ResetScroll
;
; while(1)
;
	jmp     L0400
;
; WaitFrame();
;
L0401:	jsr     _WaitFrame
;
; ResetScroll();
;
	jsr     _ResetScroll
;
; while (SCORE1 < 5 && SCORE2 < 5)
;
L0267:	lda     _SCORE1
	cmp     #$05
	bcs     L04C6
	lda     _SCORE2
	cmp     #$05
	jcc     L0479
L04C6:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; ppu_addr           = PPU_PALETTE;
;
	ldx     #$3F
	lda     #$00
	sta     _ppu_addr
	stx     _ppu_addr+1
;
; ppu_data           = PALETTES;
;
	lda     #<(_PALETTES)
	sta     _ppu_data
	lda     #>(_PALETTES)
	sta     _ppu_data+1
;
; ppu_data_size      = sizeof(PALETTES);
;
	lda     #$20
	sta     _ppu_data_size
;
; PPU_ADDRESS = (uint8_t)((PPU_NAMETABLE_0 + NAMETABLE_OFFSET) >> 8);
;
	sta     $2006
;
; PPU_ADDRESS = (uint8_t) (PPU_NAMETABLE_0 + NAMETABLE_OFFSET);
;
	sta     $2006
;
; DrawArena();
;
	jsr     _DrawArena
;
; Title_Setup();
;
	jsr     _Title_Setup
;
; Title_Loop();
;
	jsr     _Title_Loop
;
; Game_Setup();
;
	jsr     _Game_Setup
;
; Game_Loop();   
;
	jmp     _Game_Loop

.endproc

